# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tc2iqlrvar_internal <- function(Sigma, D1, D2, qLow1 = 0.25, qHigh1 = 0.75, qLow2 = 0.25, qHigh2 = 0.75) {
    .Call('_TeacupCerberus_tc2iqlrvar_internal', PACKAGE = 'TeacupCerberus', Sigma, D1, D2, qLow1, qHigh1, qLow2, qHigh2)
}

